config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dogs#index'
  resources :dogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  
  def index
    @dog = Dog.order("RANDOM()").first
  end

  def new
    @dog = Dog.new
  end

  def create
    Dog.create(dog_params)
    redirect_to root_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/index.html.erb
<head>

</head>
<body>
  <% if @dog.nil? %>
    <h1>No dogs yet! Please enter your dog's info!</h1>
  <% else %>
    <%= image_tag 'dogs.jpg', class: 'center' %>
    <br />
    <br />

    <h1><%= @dog.name %></h1>
    <h2><%= @dog.description %></h2>
  <% end %>
</body>
 

app/views/dogs/new.html.erb
<h1>Enter Your Dog's Details</h1>
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogsQuiz2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to 'Enter Dog Details', new_dog_path %>
  </body>
</html>